intervanit/config/routes.rb
Rails.application.routes.draw do
  resources :announcements

  resources :scripts

  resources :issues

  root :to => 'home#index'

  resources :reports

end

intervanit/app/models/script.rb
class Script < ActiveRecord::Base
	validates :title, presence: true
	validates :email, presence: true
	validates :author, presence: true
	validates :server, presence: true
	validates :location, presence: true
	validates :description, presence: true
end

intervanit/app/controllers/scripts_controller.rb
class ScriptsController < ApplicationController
  before_action :set_script, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [:show]
  
  # GET /scripts
  # GET /scripts.json
  def index
    @scripts = Script.all
  end

  # GET /scripts/1
  # GET /scripts/1.json
  def show
  end

  # GET /scripts/new
  def new
    @script = Script.new
  end

  # GET /scripts/1/edit
  def edit
  end

  # POST /scripts
  # POST /scripts.json
  def create
    @script = Script.new(script_params)

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, notice: 'Script was successfully created.' }
        format.json { render :show, status: :created, location: @script }
      else
        format.html { render :new }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scripts/1
  # PATCH/PUT /scripts/1.json
  def update
    respond_to do |format|
      if @script.update(script_params)
        format.html { redirect_to @script, notice: 'Script was successfully updated.' }
        format.json { render :show, status: :ok, location: @script }
      else
        format.html { render :edit }
        format.json { render json: @script.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scripts/1
  # DELETE /scripts/1.json
  def destroy
    @script.destroy
    respond_to do |format|
      format.html { redirect_to scripts_url, notice: 'Script was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_script
      @script = Script.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def script_params
      params.require(:script).permit(:title, :email, :author, :server, :location, :description, :code)
    end
     private
    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "Intervan1"
      end
    end
end

intervanit/app/helpers/scripts_helper.rb
module ScriptsHelper
end

intervanit/app/views/scripts/_form.html.erb
<%= form_for(@script) do |f| %>
  <% if @script.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@script.errors.count, "error") %> prohibited this script from being saved:</h2>

      <ul>
      <% @script.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :placeholder => "Email address of the submitter." %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author, :placeholder => "Name of the author if available." %>
  </div>
  <div class="field">
    <%= f.label :server %><br>
    <%= f.text_field :server, :placeholder => "Name of the server where the script is located." %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location, :placeholder => "Specific directory where the script is located." %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, :placeholder => "Brief description of what the script does." %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_area :code, :placeholder => "Please put code snippet here if available." %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

intervanit/app/views/scripts/edit.html.erb
<h1>Editing script</h1>

<%= render 'form' %>

<%= link_to 'Show', @script %> |
<%= link_to 'Back', scripts_path %>

intervanit/app/views/scripts/index.html.erb
<h1>Listing scripts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Email</th>
      <th>Author</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scripts.each do |script| %>
      <tr>
        <td><%= script.title %></td>
        <td><%= script.email %></td>
        <td><%= script.author %></td>
        
        <td><%= link_to 'Show', script %></td>
        <td><%= link_to 'Edit', edit_script_path(script) %></td>
        <td><%= link_to 'Destroy', script, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Script', new_script_path %><br /><br />
<%= link_to 'Back to home', controller: "home", action: "index" %>

intervanit/app/views/scripts/new.html.erb
<h1>New script</h1>

<%= render 'form' %>

<%= link_to 'Back', scripts_path %>

intervanit/app/views/scripts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @script.title %>
</p>

<p>
  <strong>Email:</strong>
  <%= @script.email %>
</p>

<p>
  <strong>Author:</strong>
  <%= @script.author %>
</p>

<p>
  <strong>Server:</strong>
  <%= @script.server %>
</p>

<p>
  <strong>Location:</strong>
  <%= @script.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @script.description %>
</p>

<p>
  <strong>Code:</strong>
  <%= @script.code %>
</p>

<%= link_to 'Edit', edit_script_path(@script) %> |
<%= link_to 'Back', scripts_path %>