intervanit/config/routes.rb
Rails.application.routes.draw do
  resources :announcements

  resources :scripts

  resources :issues

  root :to => 'home#index'

  resources :reports

end

intervanit/app/models/report.rb
class Report < ActiveRecord::Base
	validates :title, presence: true
	validates :owner, presence: true
	validates :content, presence: true
end

intervanit/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate, :except => [:show]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :owner, :content)
    end

    private
    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == "admin" && password == "Intervan1"
      end
    end

end

intervanit/app/helpers/reports_helper.rb
module ReportsHelper
end

intervanit/app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :placeholder => "ie. Kali - Web Server - 12/15/2014 - 12/22/2014" %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner, :placeholder => "Name of the original submitter of the report." %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :placeholder => "Include the overall health of the server along with any system specific information." %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

intervanit/app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

intervanit/app/views/reports/index.html.erb
<h1>Reports</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Owner</th>
      
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.title %></td>
        <td><%= report.owner %></td>
        <!--<td><%= report.content %></td>-->
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Sure about that?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %><br /><br />
<%= link_to 'Back to home', controller: "home", action: "index" %>

intervanit/app/views/reports/new.html.erb
<h1>New report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

intervanit/app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @report.title %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @report.owner %>
</p>

<p>
  <strong>Content:</strong>
  <%= @report.content %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>